version: '3.8'

services:
  dotnet-web-api:
    build:
      context: ./dotnet-web-api
      dockerfile: Dockerfile
    container_name: dotnet-web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  python-langchain-fastapi:
    build:
      context: ./python-langchain-fastapi
      dockerfile: Dockerfile
    container_name: python-langchain-fastapi
    ports:
      - "4000:8000"
    volumes:
      - ./data:/app/data
      - ./embeddings:/app/embeddings
    env_file:
      - ./python-langchain-fastapi/.env
